[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.1.0-20211123", '{"browserName": "firefox", "platformName": "linux"}',
    "selenium/standalone-chrome:4.1.0-20211123", '{"browserName": "chrome", "platformName": "linux"}',
    "selenium/standalone-edge:4.1.0-20211123", '{"browserName": "MicrosoftEdge", "platformName": "linux"}'
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://10.76.10.28:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20211123"

[relay]
# Sauce Labs server endpoint
url = "https://ondemand.us-west-1.saucelabs.com:443/wd/hub"
status-endpoint = "/status"
# Stereotypes supported by the service
configs = [
  "5", '{"browserName": "safari", "platformName": "macOS 11.00", "browserVersion": "14"}'
]